#image: python:3.6
#image: python:3
image: fkrull/multi-python:bionic

# Change pip's cache directory to be inside the project directory since we can
# only cache local items.
variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache"

# Pip's cache doesn't store the python packages
# https://pip.pypa.io/en/stable/reference/pip_install/#caching
#
# If you want to also cache the installed packages, you have to install
# them in a virtualenv and cache it as well.
cache:
  paths:
    - .cache/pip
    - venv/

before_script:
  - python -V               # Print out python version for debugging
  - pip install virtualenv
#  - virtualenv venv
#  - source venv/bin/activate
#  - pip install setuptools==39

test:
  script:
  - pip install .
  - pip install tox flake8 pytest pytest-html
  - tox

build:
  script:
    - pip install setuptools wheel
    - python setup.py sdist bdist_wheel
  artifacts:
    paths:
    - dist/*.whl
  only:
    - master
